### ISSUE TITLE
Is there a way to switch model without reloading the docker instance?

### ISSUE THREAD

**Issue by yhyu13** [mkellerman/gpt4all-ui#3]
I've set up a python script locally which contains a gui that allows modification to the compose yml's MODEL env variable, and then restart the service after model change. 

Is there a way to switch model without reloading the docker instance?

I guess I need the dockerfile launch  another local python script that intitiate the fastapi script as a subprocess.

**Comment by mkellerman** [comment]
Sorry guys, I’m not supporting this. Please check out:
https://github.com/go-skynet/LocalAI/tree/master/examples/chatbot-ui
