### ISSUE TITLE
Error fetching models. Internal Server Error

### ISSUE THREAD

**Issue by aodrasa** [mkellerman/gpt4all-ui#5]
Followed everything and getting this error

**Comment by TagorePde** [comment]
same issue here :(

**Comment by mcfnord** [comment]
i think you set it in the docker-compose.yml, but I still got the Internal Server Error 500

**Comment by mcfnord** [comment]
I think there's another localhost server at port 8000 that isn't mentioned in these installation steps.

**Comment by nutmilk10** [comment]
@mcfnord Were you able to resolve this issue?

**Comment by mcfnord** [comment]
No. Still believe what I wrote tho.

**Comment by nutmilk10** [comment]
@mkellerman any updates on this?

**Comment by dillfrescott** [comment]
Same

**Comment by mkellerman-relativity** [comment]
Sorry guys, I’m not supporting this. Please check out:
https://github.com/go-skynet/LocalAI/tree/master/examples/chatbot-ui

**Comment by mkellerman** [comment]
Sorry guys, I’m not supporting this. Please check out:
https://github.com/go-skynet/LocalAI/tree/master/examples/chatbot-ui
